// <auto-generated />
using System;
using IMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20190315082326_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMS.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Department");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<long>("IC");

                    b.Property<int>("MobileNo");

                    b.Property<string>("Pass");

                    b.Property<string>("Postcode");

                    b.Property<string>("Role");

                    b.Property<string>("Sname");

                    b.Property<int>("Spoint");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.HasKey("ID");

                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
