// <auto-generated />
using System;
using IMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20190419085524_Init5")]
    partial class Init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMS.Models.Incident", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<int>("Count");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<byte>("Images");

                    b.Property<string>("Iname");

                    b.Property<string>("Solution");

                    b.Property<string>("Status");

                    b.Property<byte>("Videos");

                    b.HasKey("ID");

                    b.ToTable("Incident");
                });

            modelBuilder.Entity("IMS.Models.IncidentTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Department");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EDate");

                    b.Property<int>("EID");

                    b.Property<string>("ESname");

                    b.Property<string>("Ename");

                    b.Property<string>("Floor");

                    b.Property<int>("IID");

                    b.Property<string>("Iname");

                    b.Property<DateTime>("SDate");

                    b.Property<int>("SID");

                    b.Property<string>("Status");

                    b.Property<string>("TableNo");

                    b.HasKey("ID");

                    b.ToTable("IncidentTask");
                });

            modelBuilder.Entity("IMS.Models.Login", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pass");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("IMS.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Department");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("Floor");

                    b.Property<string>("Gender");

                    b.Property<long>("IC");

                    b.Property<int>("MobileNo");

                    b.Property<string>("Pass");

                    b.Property<string>("Postcode");

                    b.Property<string>("Role");

                    b.Property<string>("Sname");

                    b.Property<int>("Spoint");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.Property<string>("TableNo");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("IMS.Models.TaskToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Department");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EDate");

                    b.Property<int>("EID");

                    b.Property<string>("ESname");

                    b.Property<string>("Ename");

                    b.Property<string>("Floor");

                    b.Property<int>("IID");

                    b.Property<string>("Iname");

                    b.Property<DateTime>("SDate");

                    b.Property<int>("SID");

                    b.Property<string>("Status");

                    b.Property<string>("TableNo");

                    b.HasKey("ID");

                    b.ToTable("TaskToDo");
                });
#pragma warning restore 612, 618
        }
    }
}
